from django.urls import path
from .import views
urlpatterns=[
    path('',views.index,name='index'),
    path('travel',views.travel,name='travel'),
    path('tech',views.tech,name='tech'),
    path('Technology', views.tech, name='tech'),
    path('photography',views.photography,name='photography'),
    path('about',views.about,name='about'),
    path('contact',views.contact,name='contact'),
    path('adm_login',views.adm_login,name='adm_login'),
    path('adm_logout',views.adm_logout,name='adm_logout'),
    path('adm',views.adm,name='adm'),
    path('prof', views.prof, name='prof'),
    path('cover', views.cover, name='cover'),
    path('cont_edit', views.cont_edit, name='cont_edit'),
    path('adm_post', views.adm_post, name='adm_post'),
    path('adm_update', views.adm_update, name='adm_update'),
    path('adm_delete', views.adm_delete, name='adm_delete'),
    path('adm_view', views.adm_view, name='adm_view'),
    path('adm_message', views.adm_message, name='adm_message'),
    path('adm_comment', views.adm_comment, name='adm_comment'),
    path('adm_carousel', views.adm_carousel, name='adm_carousel'),
    path('update_sub', views.update_sub, name='update_sub'),
    path('register', views.registerPage, name='registerPage'),
    path('adm_delete_sub', views.adm_delete_sub, name='adm_delete_sub'),
    path('adm_view_del/<int:id>', views.adm_view_del, name='adm_view_del'),
    path('about_me', views.about_me, name='about_me'),
    path('article/<int:id>', views.single, name='article'),
    path('comments', views.comments, name='comments'),
    path('adm_carousel_img1', views.adm_carousel_img1, name='adm_carousel_img1'),
    path('adm_carousel_img2', views.adm_carousel_img2, name='adm_carousel_img2'),
    path('adm_carousel_img3', views.adm_carousel_img3, name='adm_carousel_img3'),
]