# Generated by Django 3.1 on 2020-08-25 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_id', models.CharField(max_length=100)),
                ('auther', models.CharField(default='admin', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_img', models.ImageField(upload_to='')),
                ('like', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('message', models.CharField(max_length=100)),
                ('approval', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(default='Enquiry', max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('replay', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_name', models.CharField(max_length=100)),
                ('prof_img', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('cov_img', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('email', models.CharField(default='customer.care@blissfurious.com', max_length=100)),
                ('phone', models.CharField(default=9876543210, max_length=100)),
                ('address', models.TextField(default='Kerala')),
            ],
        ),
    ]
