# Generated by Django 3.1 on 2020-08-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bliss', '0004_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='art_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
