# Generated by Django 3.1 on 2020-08-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bliss', '0005_auto_20200825_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacts',
        ),
    ]
