# Generated by Django 3.1 on 2020-09-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bliss', '0010_contacts_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('car_img1', models.ImageField(upload_to='')),
                ('h_1', models.CharField(default='Enquiry', max_length=100)),
                ('p_1', models.CharField(default='Enquiry', max_length=100)),
                ('car_img2', models.ImageField(upload_to='')),
                ('h_2', models.CharField(default='Enquiry', max_length=100)),
                ('p_2', models.CharField(default='Enquiry', max_length=100)),
                ('car_img3', models.ImageField(upload_to='')),
                ('h_3', models.CharField(default='Enquiry', max_length=100)),
                ('p_3', models.CharField(default='Enquiry', max_length=100)),
            ],
        ),
    ]
