# Generated by Django 3.1 on 2020-09-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bliss', '0011_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='h_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='h_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='h_3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='p_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='p_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='p_3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
