# Generated by Django 3.1 on 2020-09-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bliss', '0012_auto_20200909_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
